'use strict';
// All paths are relative to report.html; no application API or CDN is required.
const $=id=>document.getElementById(id),esc=s=>String(s??'—').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),num=(x,n=2)=>typeof x==='number'?x.toFixed(n):'—';
const tab=(h,rs)=>'<div class="scroll"><table><thead><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rs.map(r=>'<tr>'+r.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const pathAnchor=n=>'path-'+n.replace(/[^a-zA-Z0-9_-]/g,x=>'_'+x.charCodeAt(0).toString(16)+'_');
let index,activeCase,caseEpoch=0,candidatePage=0,candidateData,chartData;const bodies=new Map(),chapterLoads=new Map();
async function get(file,json=false){const r=await fetch(file+'.gz');if(!r.ok)throw Error('资源加载失败：'+file+' ('+r.status+')');const bytes=new Uint8Array(await r.arrayBuffer());let text;if(bytes[0]===31&&bytes[1]===139){if(typeof DecompressionStream!=='undefined'){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));text=await new Response(stream).text()}else text=pako.ungzip(bytes,{to:'string'})}else{text=new TextDecoder().decode(bytes);if(text.startsWith('<!doctype')||text.startsWith('<html'))throw Error('静态资源映射不正确：'+file)}return json?JSON.parse(text):text}
function failure(el,e,retry){el.innerHTML='<p class="error">'+esc(e.message)+'</p>';const b=document.createElement('button');b.textContent='重试';b.className='retry';b.addEventListener('click',retry);el.appendChild(b)}
async function groupData(group){if(bodies.has(group)){const value=bodies.get(group);bodies.delete(group);bodies.set(group,value);return value}const value=await get('evidence/'+group+'.json',true);bodies.set(group,value);while(bodies.size>4)bodies.delete(bodies.keys().next().value);return value}
async function fillBody(el){if(el.dataset.loaded==='true')return;if(el._loading)return el._loading;const slot=el.querySelector('.deferred-slot');if(!slot)return;el._loading=(async()=>{try{const group=await groupData(el.dataset.group);slot.innerHTML=group.bodies[el.dataset.body];el.dataset.loaded='true';await afterInsert(slot)}catch(e){el.dataset.loaded='false';failure(slot,e,()=>fillBody(el))}finally{el._loading=null}})();return el._loading}
async function afterInsert(root){const candidate=root.querySelector('#candidateTable');if(candidate&&activeCase)await ensureCandidates();const macro=root.querySelector('#macro');if(macro&&index)macroRows()}
async function chapter(n){if(chapterLoads.has(n))return chapterLoads.get(n);const el=$('chapter-body-'+n);if(!el)return;const work=(async()=>{try{el.innerHTML=await get('chapters/'+n+'.html');el.classList.remove('loading');await afterInsert(el)}catch(e){chapterLoads.delete(n);failure(el,e,()=>chapter(n))}})();chapterLoads.set(n,work);return work}
async function selectCase(cid){if(!index.cases.some(c=>c.id===cid))return;const epoch=++caseEpoch;activeCase=cid;candidateData=null;chartData=null;candidatePage=0;$('case').value=cid;$('caseDetail').innerHTML='<p class="loading">正在加载用例…</p>';$('budget').innerHTML='';try{const [html,budget]=await Promise.all([get('cases/'+cid+'.html'),get('cases/'+cid+'-budget.html')]);if(epoch!==caseEpoch)return;$('caseDetail').innerHTML=html;$('budget').innerHTML=budget}catch(e){if(epoch===caseEpoch)failure($('caseDetail'),e,()=>selectCase(cid))}}
async function jumpCase(cid,marker){await selectCase(cid);if(activeCase!==cid)return;const anchor=pathAnchor(marker);let target=$(anchor);if(!target){const group=await groupData(cid);for(const key of group.routes[anchor]||[]){const el=document.querySelector('details[data-group="'+cid+'"][data-body="'+key+'"]');if(el){el.open=true;await fillBody(el)}}target=$(anchor)}if(!target)target=$('caseDetail');for(let p=target.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS'){p.open=true;await fillBody(p)}target.scrollIntoView({behavior:'smooth',block:'center'})}
async function jumpPlan(id){await chapter(3);const el=$(id);if(el){if(el.tagName==='DETAILS'){el.open=true;await fillBody(el)}el.scrollIntoView({behavior:'smooth',block:'start'})}}
function decodeCandidates(data){return data.rows.map(row=>{let m=Object.fromEntries(data.fields.map((k,i)=>[k,row[i]]));for(const k of ['name','stage','thread'])m[k]=data.pool[m[k]];for(const k of ['chain','reasons'])m[k]=m[k].map(i=>data.pool[i]);m.children=m.children.map(a=>({name:data.pool[a[0]],count:a[1],totalMs:a[2],maxMs:a[3]}));return m})}
async function ensureCandidates(){const cid=activeCase,epoch=caseEpoch;if(!candidateData){const data=await get('candidates/'+cid+'.json',true);if(epoch!==caseEpoch)return;candidateData={rows:decodeCandidates(data),markerCount:data.markerCount}}renderCandidates()}
function renderCandidates(){if(!candidateData||!$('candidateTable'))return;const query=($('markerFilter')?.value||'').toLowerCase(),order=$('markerSort')?.value||'wholeMeanMs',rows=candidateData.rows.filter(m=>!query||[m.name,m.stage,...m.chain].join(' ').toLowerCase().includes(query)).sort((a,b)=>b[order]-a[order]),pages=Math.max(1,Math.ceil(rows.length/100));candidatePage=Math.min(candidatePage,pages-1);
 const headers=['真实marker','执行阶段','全程均ms/帧','出现帧均ms','出现/总帧','全程P50 / P95 ms','单次均ms','单次max / 帧','同帧累计max ms','Self全程均ms','为何入选 / 峰值来源'];
 $('candidateTable').innerHTML='<p>匹配'+rows.length+'项 / 本用例'+candidateData.rows.length+'候选 / 扫描'+candidateData.markerCount+'个marker；第'+(candidatePage+1)+'/'+pages+'页（每页100项）。候选含上下游，不是独立优化清单。</p>'+tab(headers,rows.slice(candidatePage*100,(candidatePage+1)*100).map(m=>[esc(m.name),esc(m.stage),num(m.wholeMeanMs,3),num(m.appearingMeanMs,3),m.appearingFrames+'/'+m.totalFrames+' ('+num(100*m.appearingFrames/m.totalFrames,1)+'%)',num(m.wholeP50Ms)+' / '+num(m.wholeP95Ms),num(m.singleMeanMs,4),num(m.singleMaxMs)+' / F'+m.peakFrame,num(m.frameMaxMs),num(m.selfWholeMeanMs,3),'<details><summary>'+esc(m.reasons.join('；'))+'</summary><p class="path">'+m.chain.map(esc).join(' → ')+'</p>'+tab(['同次直接子项','N','累计ms'],m.children.map(x=>[esc(x.name),x.count,num(x.totalMs)]))+'</details>']))}
function visibleCases(){const q=($('filter')?.value||'').toLowerCase(),cohort=$('cohort')?.value||'';return index.cases.filter(c=>(!cohort||c.cohort===cohort)&&(!q||[c.id,c.label,c.cohort,c.condition].join(' ').toLowerCase().includes(q)))}
function macroRows(){const el=$('macro');if(!el||!index)return;el.innerHTML=tab(['采样场景 / 轮次','条件','FPS','帧均ms','P95ms','DrawCall均','面数均'],visibleCases().map(c=>['<button data-case="'+c.id+'">'+esc(c.label)+'</button>',esc(c.condition),num(c.fps),num(c.meanMs),num(c.p95Ms),num(c.drawCalls,0),num(c.triangles,0)]))}
function exportCsv(){const rows=[['场景','条件分组','条件','编号','有效FPS','全文件FPS','帧均ms','P95ms','DrawCall均','面数均'],...visibleCases().map(c=>[c.label,c.cohort,c.condition,c.id,c.fps,c.wholeFps,c.meanMs,c.p95Ms,c.drawCalls,c.triangles])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ferry-stress-scenes.csv';a.click();URL.revokeObjectURL(a.href)}
function lineFigure(points,label,budget=null){const p=points.filter(x=>Number.isFinite(x[0])&&Number.isFinite(x[1]));if(!p.length)return '<p class="muted">该指标缺测</p>';const x0=p[0][0],x1=p.at(-1)[0],max=Math.max(.001,...p.map(x=>x[1]),budget||0)*1.08,X=x=>70+(x-x0)/Math.max(.001,x1-x0)*780,Y=y=>255-y/max*205;return '<svg class="trend-svg" viewBox="0 0 920 300" role="img" aria-label="'+esc(label)+'">'+[0,.25,.5,.75,1].map(k=>'<line x1="70" x2="850" y1="'+Y(k*max)+'" y2="'+Y(k*max)+'" stroke="#344d5c"/><text x="60" y="'+(Y(k*max)+5)+'" fill="#b2c7d5" text-anchor="end">'+num(k*max)+'</text>').join('')+(budget===null?'':'<line x1="70" x2="850" y1="'+Y(budget)+'" y2="'+Y(budget)+'" stroke="#f5bf77" stroke-dasharray="6"/><text x="75" y="'+(Y(budget)-5)+'" fill="#f5bf77">30FPS · 33.33ms</text>')+'<polyline fill="none" stroke="#77dccc" stroke-width="1.6" points="'+p.map(x=>X(x[0])+','+Y(x[1])).join(' ')+'"/><text x="70" y="285" fill="#b2c7d5">'+num(x0)+'s</text><text x="850" y="285" fill="#b2c7d5" text-anchor="end">'+num(x1)+'s</text></svg>'}
function frameTrend(c,key){if(key==='playerLoopMs'&&c.accountingFrames.length){const fi=c.frameColumns.indexOf('frame'),mi=c.frameColumns.indexOf('frameMs'),si=c.frameColumns.indexOf('seconds');let t=0;const times=new Map(c.frames.map(f=>{t+=(f[mi]||0)/1000;return [f[fi],si>=0?f[si]:t]}));return lineFigure(c.accountingFrames.map(f=>[times.get(f[0]),f[1]]),'PlayerLoop ms',33.333)}const col=c.frameColumns.indexOf(key);if(col<0)return '<p class="muted">没有该指标的逐帧计时</p>';const si=c.frameColumns.indexOf('seconds'),mi=c.frameColumns.indexOf('frameMs');let t=0;return lineFigure(c.frames.map(f=>{t+=(f[mi]||0)/1000;return [si>=0?f[si]:t,f[col]]}),key,key==='frameMs'?33.333:null)}
function macroTrend(c,key){const start=c.samples?.[0]?.realtime??0;return lineFigure(c.samples.map(s=>{let v;if(key==='drawCalls')v=s.render?.drawCalls;if(key==='triangles')v=s.render?.triangles/1e4;if(key==='entityQueue')v=s.queues?.entity;if(key==='armies')v=s.battle?.armies;if(key==='soldiers')v=s.battle?.soldiers;if(['queued','dispatchReturned','knownOutcome'].includes(key)){const ms=s.telemetry?.intervalMs;v=ms>0?s.telemetry?.values?.task?.[key]*1000/ms:undefined}return [s.realtime-start,v]}),key)}
async function updateChart(id){const epoch=caseEpoch,cid=activeCase;if(!chartData){const c=await get('charts/'+cid+'.json',true);if(epoch!==caseEpoch)return;chartData=c}if(epoch!==caseEpoch)return;const isFrame=id==='frameMetric';$(isFrame?'frameTrend':'macroTrend').innerHTML=(isFrame?frameTrend:macroTrend)(chartData,$(id).value)}
document.addEventListener('toggle',e=>{if(e.target.tagName==='DETAILS'&&e.target.open&&e.target.dataset.body)fillBody(e.target)},true);
document.addEventListener('change',e=>{if(e.target.id==='case')selectCase(e.target.value);if(['frameMetric','macroMetric'].includes(e.target.id))updateChart(e.target.id).catch(err=>failure($(e.target.id==='frameMetric'?'frameTrend':'macroTrend'),err,()=>updateChart(e.target.id)));if(e.target.id==='markerSort'){candidatePage=0;renderCandidates()}if(e.target.id==='cohort')macroRows()});
let searchTimer;document.addEventListener('input',e=>{if(e.target.id==='markerFilter'){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{candidatePage=0;renderCandidates()},120)}if(e.target.id==='filter')macroRows()});
document.addEventListener('click',async e=>{const el=e.target.closest('button,a');if(!el)return;try{if(el.dataset.evidenceCase){e.preventDefault();await jumpCase(el.dataset.evidenceCase,el.dataset.evidenceMarker)}else if(el.dataset.case){await selectCase(el.dataset.case);$('caseDetail').scrollIntoView({behavior:'smooth'})}else if(el.id==='markerPrev'){candidatePage=Math.max(0,candidatePage-1);renderCandidates()}else if(el.id==='markerNext'){candidatePage++;renderCandidates()}else if(el.id==='export')exportCsv();else if(el.getAttribute('href')?.startsWith('#plan-')){e.preventDefault();await jumpPlan(el.getAttribute('href').slice(1))}else if(el.getAttribute('href')?.startsWith('#chapter-')){const n=Number(el.getAttribute('href').slice(9));if(n!==2&&n!==5)await chapter(n)}}catch(err){console.error(err)}});
async function init(){try{index=await get('index.json',true);await Promise.all([chapter(1),selectCase(index.defaultCase)]);if(typeof IntersectionObserver!=='undefined'){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){chapter(e.target.dataset.chapter);observer.unobserve(e.target)}},{rootMargin:'250px'});for(const el of document.querySelectorAll('[data-chapter]'))if(el.dataset.chapter!=='1')observer.observe(el)}else for(const n of [3,4,6,7,8])await chapter(n);if(location.hash.startsWith('#plan-'))await jumpPlan(location.hash.slice(1))}catch(e){failure($('caseDetail'),e,init)}}
if(location.protocol==='file:'){
 $('case').value='recheck_A_static_r1';
 $('caseDetail').innerHTML='<div class="card"><p><b>请通过本地预览或服务器地址打开报告。</b></p><p>浏览器无法通过 file:// 读取按需加载的数据。请双击同目录的 <b>start-preview.cmd</b>，它会启动本地预览并打开浏览器。</p><p>本地地址：<a href="http://127.0.0.1:18106/report.html">http://127.0.0.1:18106/report.html</a></p></div>';
 for(const el of document.querySelectorAll('[data-chapter]'))el.textContent='通过本地预览打开后显示内容。';
}else init();
