const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),assert=require('assert');
const {chromium}=require('C:/Users/garyychen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'../..'),ID='city-gpu-compare-20261002',PREFIX='/cpu/report/'+ID+'/',DIST=path.join(ROOT,'web/dist/client'),PUB=path.join(ROOT,'web/public/report',ID),OUT=path.join(ROOT,'artifacts/city_clean_compare_20261002');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.csv':'text/csv; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(!url.pathname.startsWith('/cpu/')){res.writeHead(404);res.end();return;}let f=path.resolve(DIST,decodeURIComponent(url.pathname.slice('/cpu/'.length)));if(!f.startsWith(DIST+path.sep)){res.writeHead(403);res.end();return;}if(!fs.existsSync(f)||!fs.statSync(f).isFile()){if(url.pathname==='/cpu/performance-reports'){f=path.join(DIST,'index.html');}else{res.writeHead(404);res.end();return;}}res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res);});
(async()=>{let browser;await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{
 const manifest=JSON.parse(fs.readFileSync(path.join(PUB,'manifest.json'),'utf8')),catalogRes=await fetch(base+'/cpu/report/catalog.json');assert(catalogRes.ok&&catalogRes.headers.get('content-type').includes('application/json'));const catalog=await catalogRes.json();assert.strictEqual(catalog.length,2);const entry=catalog.find(x=>x.id===ID),old=catalog.find(x=>x.id==='ferry-stress-20261006');assert(entry&&old);assert.strictEqual(entry.href,PREFIX+'report.html');assert((await fetch(base+old.href)).ok);
 let verified=0;for(let i=0;i<manifest.files.length;i+=12)await Promise.all(manifest.files.slice(i,i+12).map(async item=>{const response=await fetch(base+PREFIX+item.file);assert(response.ok,item.file);const bytes=Buffer.from(await response.arrayBuffer());assert.strictEqual(bytes.length,item.bytes,item.file);assert.strictEqual(crypto.createHash('sha256').update(bytes).digest('hex'),item.sha256,item.file);verified++;}));
 browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/cpu/performance-reports');await page.getByText(entry.title,{exact:true}).waitFor();await page.getByText(old.title,{exact:true}).waitFor();const open=page.locator('a[href="'+entry.href+'"]');assert.strictEqual(await open.count(),1);assert.strictEqual(await open.getAttribute('target'),'_blank');await page.screenshot({path:path.join(OUT,'public_catalog_preview.png')});
 const popupPromise=page.waitForEvent('popup');await open.click();const report=await popupPromise;report.on('pageerror',e=>errors.push(e.message));await report.waitForLoadState('load');assert.strictEqual(new URL(report.url()).pathname,entry.href);assert((await report.locator('#resultcount').textContent()).includes('888'));
 await report.locator('#case').selectOption('empire2');await report.locator('#encoder').selectOption('1');assert((await report.locator('#resultcount').textContent()).includes('401'));await report.locator('#query').fill('SM_Water_Plane_LOD2');assert((await report.locator('#resultcount').textContent()).includes('3 条'));await report.locator('#query').fill('');await report.locator('#encoder').selectOption('all');await report.locator('#case').selectOption('all');await report.locator('#dataset').selectOption('pipelines');assert((await report.locator('#resultcount').textContent()).includes('179'));await report.locator('#dataset').selectOption('memory');assert((await report.locator('#resultcount').textContent()).includes('3479'));
 const cards=await report.locator('#shader-complexity').innerText();for(const x of ['2.13倍','2.32倍','2.98倍','1.65倍'])assert(cards.includes(x));await report.locator('#shader-complexity').scrollIntoViewIfNeeded();await report.screenshot({path:path.join(OUT,'public_shader_metrics_preview.png')});
 const images=await report.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.getAttribute('src'),loaded:x.complete&&x.naturalWidth>0})));assert(images.every(x=>x.loaded));const shaderHref=await report.locator('#shaders a[href*=".metal.html"]').first().getAttribute('href');const shader=await fetch(new URL(shaderHref,report.url()));assert(shader.ok);assert((await shader.text()).includes('id="L1"'));const csvHref=await report.locator('a[href$="mesh_triangles.csv"]').first().getAttribute('href');assert((await fetch(new URL(csvHref,report.url()))).ok);
 await report.setViewportSize({width:800,height:1000});await report.reload();assert(!(await report.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));assert.deepStrictEqual(errors,[]);
 const proof={passed:true,checkedAt:'2026-10-08',builtAssetsVerifiedByHttpAndSha256:verified,catalogReports:catalog.length,catalogContentType:'application/json',existingReportAccessible:true,performanceReportsPageListsBothReports:true,openReportInNewTab:true,draws:888,empire2ColorDraws:401,actualPso:179,resources:3479,emphasizedShaderMetrics:true,images,sourceAndCsvLinksPass:true,narrowLayoutPass:true,pageErrors:errors,remoteDeploymentPerformed:false};fs.writeFileSync(path.join(PUB,'http_validation.json'),JSON.stringify(proof,null,2));fs.writeFileSync(path.join(DIST,'report',ID,'http_validation.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
