const fs=require('fs'),path=require('path'),crypto=require('crypto'),zlib=require('zlib'),vm=require('vm'),assert=require('assert'),http=require('http');
const R=path.resolve(process.argv[2]||'web/public/report/ferry-stress-20261006'),S=path.resolve(process.argv[3]||'output/map_recheck_20261006_213000'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(fs.readFileSync(path.join(R,'manifest.json'),'utf8')),read=n=>zlib.gunzipSync(fs.readFileSync(path.join(R,n+'.gz'))).toString('utf8'),json=n=>JSON.parse(read(n));
for(const f of manifest.files){const p=path.resolve(R,f.file);assert(p.startsWith(R+path.sep));const bytes=fs.readFileSync(p);assert.strictEqual(bytes.length,f.bytes);assert.strictEqual(hash(bytes),f.sha256);assert(!/\.(raw|pdata|pftrace|so|sqlite|zip)$/i.test(f.file));if(f.file.endsWith('.gz'))assert.strictEqual(zlib.gunzipSync(bytes).length,f.uncompressedBytes)}
const raw=fs.readFileSync(path.join(S,'report-data.json'),'utf8'),D=JSON.parse(raw);assert.strictEqual(hash(raw),manifest.sourceSha256);const template=fs.readFileSync(path.join(S,'report_template_v9.html'),'utf8'),code=template.match(/<\/script><script>([\s\S]*?)<\/script>/)[1];
const els=new Map();class El{constructor(id){this.id=id;this.value='';this.innerHTML='';this.textContent='';this.handlers={}}insertAdjacentHTML(p,s){this.innerHTML+=s}addEventListener(k,f){this.handlers[k]=f}scrollIntoView(){}click(){}}
const document={getElementById(id){if(!els.has(id))els.set(id,new El(id));return els.get(id)},createElement(){return new El('download')}};document.getElementById('reportData').textContent=raw;
const ctx=vm.createContext({document,Blob:class{},URL:{createObjectURL(){return'blob:qa'},revokeObjectURL(){}}});new vm.Script(code).runInContext(ctx);const run=s=>vm.runInContext(s,ctx);
const externalImages=html=>html.replace(/src="data:image\/([^;]+);base64,([^"]+)"/g,(_,type,b64)=>`src="images/${hash(Buffer.from(b64,'base64')).slice(0,20)}.${type==='jpeg'?'jpg':type}" loading="lazy" decoding="async"`);
let deferredBodies=0,expandedBytes=0,compactBytes=0,candidates=0;
function expand(html,group){return html.replace(/<details([^>]*?) data-group="([^"]+)" data-body="([^"]+)">([\s\S]*?<\/summary>)<div class="deferred-slot"><\/div><\/details>/g,(_,attrs,scope,key,head)=>{assert.strictEqual(scope,group.name);assert(group.bodies[key]!==undefined);deferredBodies++;return '<details'+attrs+'>'+head+expand(group.bodies[key],group)+'</details>'})}
for(const c of D.cases){document.getElementById('case').value=c.id;run('detail()');const lite=read('cases/'+c.id+'.html'),group=json('evidence/'+c.id+'.json');group.name=c.id;const restored=expand(lite,group),expected=externalImages(els.get('caseDetail').innerHTML);assert.strictEqual(restored,expected,'HTML loss '+c.id);assert(!restored.includes('NaN'));assert(!/<script\b|src="data:/i.test(restored));compactBytes+=Buffer.byteLength(lite);expandedBytes+=Buffer.byteLength(restored);
 for(const [anchor,route] of Object.entries(group.routes)){let text=lite;for(const key of route){assert(text.includes('data-body="'+key+'"'));text=group.bodies[key]}assert(text.includes('id="'+anchor+'"'))}
 const chart=json('charts/'+c.id+'.json');assert.deepStrictEqual(chart.frames,c.frames);assert.deepStrictEqual(chart.samples,c.samples);assert.deepStrictEqual(chart.accountingFrames,D.accounting.cases[c.id].frames||[]);
 const stats=json('candidates/'+c.id+'.json'),original=run(`ensureCase(${JSON.stringify(c.id)})`);assert.strictEqual(stats.rows.length,original.candidates.length);candidates+=stats.rows.length;
 assert.strictEqual(read('cases/'+c.id+'-budget.html'),els.get('budget').innerHTML);
}
assert.strictEqual(candidates,42978);const index=json('index.json');assert.strictEqual(index.cases.length,115);assert.strictEqual(index.title,'抢渡口压测性能采集报告');assert.strictEqual(index.environment.model,'24072PX77C');assert.strictEqual(index.environment.version,'0.0.999.1020');assert.strictEqual(index.environment.quality,'精致');
const main=fs.readFileSync(path.join(R,'report.html'),'utf8');assert(!main.includes('reportData'));for(const x of ['抢渡口压测性能采集报告','24072PX77C','0.0.999.1020','精致'])assert(main.includes(x));assert(Buffer.byteLength(main)<20000);assert(compactBytes<expandedBytes/5);
const prefix='/cpu/report/ferry-stress-20261006/',server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]).slice(prefix.length),file=path.resolve(R,name);if(!req.url.startsWith(prefix)||!file.startsWith(R+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':file.endsWith('.gz')?'application/gzip':file.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream'});fs.createReadStream(file).pipe(res)});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port+prefix;try{
 const doc={addEventListener(){},getElementById(){return new El('test')}},client=fs.readFileSync(path.join(R,'report.js'),'utf8').replace(/\ninit\(\);\s*$/,'');const browser=vm.createContext({document:doc,fetch:file=>fetch(base+file),Blob,Response,TextDecoder,DecompressionStream,URL,console,setTimeout,clearTimeout,location:{hash:''}});new vm.Script(fs.readFileSync(path.join(R,'vendor/pako_inflate.min.js'),'utf8')).runInContext(browser);new vm.Script(client).runInContext(browser);
 const browserIndex=await vm.runInContext("get('index.json',true)",browser);assert.strictEqual(browserIndex.cases.length,115);browser.DecompressionStream=undefined;const fallback=await vm.runInContext("get('index.json',true)",browser);assert.strictEqual(fallback.title,index.title);await assert.rejects(vm.runInContext("get('missing.json',true)",browser));
 for(const cid of ['recheck_A_move_r3','recheck_A_zoom_r1']){const packed=json('candidates/'+cid+'.json');browser.packed=packed;const decoded=vm.runInContext('decodeCandidates(packed)',browser),reference=run(`ensureCase(${JSON.stringify(cid)}).candidates`);for(let i=0;i<decoded.length;i++)for(const field of packed.fields)assert.strictEqual(JSON.stringify(decoded[i][field]),JSON.stringify(reference[i][field]));browser.chart=json('charts/'+cid+'.json');for(const metric of ['frameMs','playerLoopMs'])assert(!vm.runInContext(`frameTrend(chart,${JSON.stringify(metric)})`,browser).includes('NaN'));for(const metric of ['drawCalls','triangles','dispatchReturned'])assert(!vm.runInContext(`macroTrend(chart,${JSON.stringify(metric)})`,browser).includes('NaN'))}
 const defaultHtml=read('cases/'+index.defaultCase+'.html'),imageBytes=[...new Set([...defaultHtml.matchAll(/src="(images\/[^"]+)"/g)].map(x=>x[1]))].reduce((sum,name)=>sum+fs.statSync(path.join(R,name)).size,0),initialFiles=['report.html','report.js','styles.css','vendor/pako_inflate.min.js','index.json.gz','cases/'+index.defaultCase+'.html.gz','cases/'+index.defaultCase+'-budget.html.gz','chapters/1.html.gz'],initialBytes=initialFiles.reduce((sum,name)=>sum+fs.statSync(path.join(R,name)).size,0)+imageBytes;assert(initialBytes<1000000);
 const proof={passed:true,revision:10,cases:115,candidates,allCaseHtmlLosslessAgainstV9:true,allFrameAndTelemetryDataUnchanged:true,budgetHtmlUnchanged:true,sourceSha256:manifest.sourceSha256,deferredBodies,compactCaseHtmlBytes:compactBytes,expandedCaseHtmlBytes:expandedBytes,totalDeployBytes:manifest.totalBytes,initialWithDefaultCaseAndAllItsImagesBytes:initialBytes,htmlBytes:Buffer.byteLength(main),httpSubpathResourcesPass:true,nativeAndFallbackGzipDecodingPass:true,allEvidenceRoutesPass:true,noRawTracesSymbolsOrOfflineBackups:true,kind:'Lossless HTML reconstruction, data comparison and static HTTP/client loader checks; not a browser scrolling benchmark or remote deployment'};fs.writeFileSync(path.join(R,'validation.json'),JSON.stringify(proof,null,2));console.log(proof);
 }finally{await new Promise(resolve=>server.close(resolve))}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
